services:
  - type: web
    name: resume-analyzer-tracker
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      python -m spacy download en_core_web_md
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: resume-tracker-db
          property: connectionString
    autoDeploy: false

  - type: pgsql
    name: resume-tracker-db
    databaseName: tracker
    user: postgres
